version: '2'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_HOST: mysql_db:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: mauFJcuf5dhRMQrjj
      MYSQL_DATABASE: book_db
    depends_on:
      mysql_db:
        condition: service_healthy
  mysql_db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=book_db
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
      - MYSQL_USER=book_user
      - MYSQL_PASSWORD=123
    mem_limit: 512M
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local